export enum AuditAction {
  AGENT_REGISTERED = 'AGENT_REGISTERED',
  AGENT_HEARTBEAT = 'AGENT_HEARTBEAT',
  RELEASE_CREATED = 'RELEASE_CREATED',
  RELEASE_PUBLISHED = 'RELEASE_PUBLISHED',
  RELEASE_ARCHIVED = 'RELEASE_ARCHIVED',
  ARTIFACT_UPLOADED = 'ARTIFACT_UPLOADED',
  DEPLOYMENT_CREATED = 'DEPLOYMENT_CREATED',
  DEPLOYMENT_STARTED = 'DEPLOYMENT_STARTED',
  DEPLOYMENT_SUCCESS = 'DEPLOYMENT_SUCCESS',
  DEPLOYMENT_FAILED = 'DEPLOYMENT_FAILED',
  DEPLOYMENT_CANCELLED = 'DEPLOYMENT_CANCELLED',
  USER_LOGIN = 'USER_LOGIN',
}