export enum DeploymentStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  DOWNLOADING = 'DOWNLOADING',
  VERIFYING = 'VERIFYING',
  INSTALLING = 'INSTALLING',
  STARTING = 'STARTING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}